### ISSUE TITLE
.NET - Potentially large memory allocation at each call

### ISSUE THREAD

**Issue by ArtemAvramenko** [anyascii/anyascii#18]
In the code there is such a thing:
```cs
private static ReadOnlySpan<byte> Bank => new byte[64436]
{
    83, 104, 99, 104, 39, 101, 117, 101, 117, 101,
    // .. 62 Kb more data
};
```

Probably the expectation here was that the array would be created once. But in fact it will be created every time the property is accessed, because the expression-bodied property is just syntactic sugar for `get { return new ... }`

To avoid potential memory problems you should replace this with:
```cs
private static ReadOnlySpan<byte> Bank { get; } = new byte[]
{
...
```

**Comment by hunterwb** [comment]
Due to compiler optimizations none of the arrays are allocated or even exist, the spans refer directly to static data
https://github.com/dotnet/csharplang/issues/5295
https://github.com/dotnet/roslyn/pull/24621
A large static dictionary causes problems
https://github.com/dotnet/runtime/issues/54688

**Comment by ArtemAvramenko** [comment]
Oh, I missed that news about compiler optimization, it's really confusing in its non-obviousness. Thanks for the useful information
