### ISSUE TITLE
Python package missing py.typed marker

### ISSUE THREAD

**Issue by AWhetter** [anyascii/anyascii#19]
Currently when running mypy against a library that uses anyascii will result in the following error:

```
$ mypy mypackage
mypackage/mymodule.py:6: error: Skipping analyzing "anyascii": module is installed, but missing library stubs or py.typed marker  [import]
mypackage/mymodule.py:6: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

As noted in PEP-561 (https://peps.python.org/pep-0561/#packaging-type-information) and the mypy documentation linked above, the presence of a py.typed file is necessary for mypy to use the type annotation that's already present in anyascii.

**Comment by hunterwb** [comment]
Thanks
