### ISSUE TITLE
Targeting Framework not Supported

### ISSUE THREAD

**Issue by VoroninDA** [anyascii/anyascii#5]
Hello,

We are trying to add the Nuget Package AnyAscii to our C# .Net Standard 2.1 class library.

![image](https://user-images.githubusercontent.com/23041974/132355481-1cf690be-f88c-4d2d-8970-eafbe2a7c683.png)
We noticed that the package wasn't compatible even though we are able to clone your repo and take a dependency on the any-ascii csproj inside the repository.

**Comment by hunterwb** [comment]
AnyAscii 0.2.0 supports .NET Standard 1.0
AnyAscii 0.3.0 supports .NET 5.0 or .NET Core 3.0 because it uses System.Text.Rune and System.ReadOnlySpan
0.3.0 should have much better performance

**Comment by VoroninDA** [comment]
Yes but if it supports .NET 5, shouldn't you add Standard 2.1 if you add Core 3.0?
For .NET 5 code, net5.0 replaces both netcoreapp and netstandard TFMs.
https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-5-and-net-standard

**Comment by hunterwb** [comment]
.NET Standard 2.1 does not support System.Text.Rune while .NET Core 3.0 does

**Comment by VoroninDA** [comment]
Thank you. What advantages does this new implementation have over the previous implementation?

**Comment by VoroninDA** [comment]
Thank you for your diligence.
