### ISSUE TITLE
Possible to host Java build artifacts on Maven Central?

### ISSUE THREAD

**Issue by breandan** [anyascii/anyascii#6]
Thanks for maintaining this great project! We are using AnyAscii for [our editor plugin](https://github.com/acejump/acejump), but flaky JitPack downloads seem to be causing unstable CI builds. Would it be possible to use another hosting provider, such as Maven Central?

**Comment by hunterwb** [comment]
Now in Maven Central in 0.3.1

**Comment by breandan** [comment]
Thank you!
